apiVersion: apps/v1
kind: Deployment
metadata:
  name: ceph-exporter
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: ceph-exporter
  replicas: 1
  template:
    metadata:
      labels:
        app: ceph-exporter
    spec:
      containers:
      - image: harbor.oceanai.com.cn/k8s_ceph/ceph_exporter:191016
        imagePullPolicy: IfNotPresent
        name: ceph-exporter
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - mountPath: /etc/ceph
          name: ceph-conf
      hostNetwork: true
      nodeSelector:
        ceph-osd: ceph-osd
      volumes:
      - hostPath:
          path: /etc/ceph
        name: ceph-conf
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  labels:
    app: prometheus
    chart: prometheus-7.1.4
    component: "node-exporter"
    heritage: Tiller
    release: monitor
    k8s-app: ceph-exporter
  name: ceph-exporter
  namespace: monitoring
spec:
  clusterIP: None
  ports:
  - name: ceph-metrics
    port: 9128
    protocol: TCP
    targetPort: 9128
  selector:
    app: ceph-exporter
  type: ClusterIP
