apiVersion: v1
kind: Pod
metadata:
  labels:
    app: ceph-exporter
  name: ceph-exporter
  namespace: monitoring
  #ownerReferences:
  #- apiVersion: extensions/v1beta1
  #  blockOwnerDeletion: true
  #  controller: true
  #  kind: DaemonSet
  #  name: ceph-exporter
spec:
  containers:
  - image: harbor.oceanai.com.cn/k8s_ceph/ceph_exporter:191016
    imagePullPolicy: IfNotPresent
    name: ceph-exporter
    resources:
      limits:
        cpu: 100m
        memory: 200Mi
      requests:
        cpu: 100m
        memory: 200Mi
    volumeMounts:
    - mountPath: /etc/ceph
      name: ceph-conf
  hostNetwork: true
  nodeName: cloud08   #Ceph宿主机的ip
  nodeSelector:
    kubernetes.io/hostname: cloud08  #Ceph宿主机的ip
  restartPolicy: Always
  serviceAccount: default
  serviceAccountName: default
  volumes:
  - hostPath:
      path: /etc/ceph
    name: ceph-conf
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  labels:
    app: prometheus
    chart: prometheus-7.1.4
    component: "node-exporter"
    heritage: Tiller
    release: monitor
    k8s-app: ceph-exporter
  name: ceph-exporter
  namespace: monitoring
spec:
  clusterIP: None
  ports:
  - name: ceph-metrics
    port: 9128
    protocol: TCP
    targetPort: 9128
  selector:
    app: ceph-exporter
  type: ClusterIP
