apiVersion: v1
kind: Pod
metadata:
  name: get-pvc-data
  labels:
    name: get-pvc-data
spec:
  containers:
  - name: get-pvc-data
    image: harbor.oceanai.com.cn/k8s_ceph/getpvcdata:191014
    volumeMounts:
    - name: ceph-rbd
      mountPath: /pvc_data
  volumes:
  - name: ceph-rbd
    persistentVolumeClaim:
      claimName: ceph-rbd-claim
